### ISSUE TITLE
Позволяет ли протокол отладки получать в замере количество входов в метод?

### ISSUE THREAD

**Issue by tormozit** [yukon39/bsl-debug-server#9]
В замере производительности отладчике конфигуратора это невозможно узнать. Количество выходов из метода можно узнать по количеству выполнений "КонецПроцедуры/КонецФункции". Нужно знать количество входов, чтобы посчитать точный баланс (разность) между входами и выходами и тем самым сильно сузить область поиска строки кода, в которой возникает зависание или неуловимый сбой.

**Comment by yukon39** [comment]
Сам протокол не позволяет: замер производительности возвращает информацию содержащую ИД модуля, и данные о том, какие строки (по номеру строки) выполнялись (см. объект  PerformanceInfoModule).

Сведения о тексте строки протокол отладки тоже не содержит. Для замера производительности выполняемом из Конфигуратора эти сведения подготавливаются Конфигуратором, т.к. он имеет доступ к текстам модулей. Отладчик сам по себе с текстами модулей не работает.

**Comment by tormozit** [comment]
ясно
